---
kind: TanzuKubernetesCluster                 
apiVersion: run.tanzu.vmware.com/v1alpha1    
metadata:
  name: tkg-cluster-01                                
spec:
  distribution:
    #version: v1.16.4+vmware.1-tkg.1.886c781
    version: v1.16.8
  topology:
    controlPlane:
      count: 3 # 3-nodes
      class: best-effort-xsmall
      storageClass: vsan-ftt-0
    workers:
      count: 3 # 3-nodes                     
      class: best-effort-xsmall
      storageClass: vsan-ftt-0
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"] # Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/16"]    # Cannot overlap with Supervisor Cluster
    storage:
      classes: ["vsan-ftt-0"]           # Named PVC storage classes
      defaultClass: vsan-ftt-0          # Default PVC storage class

