---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-user-gowatana
  namespace: demo
roleRef:
  kind: ClusterRole
  name: edit                             #Default ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:gowatana@go-lab.jp           #sso:<username>@<domain>
  apiGroup: rbac.authorization.k8s.io

