---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:privileged
rules:
- resourceNames:
  - vmware-system-privileged
  apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use

