---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:authenticated
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: psp:vmware-system-restricted
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated

